# Generated by Django 5.0.3 on 2024-06-02 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('department', models.CharField(choices=[('General Medicine', 'General Medicine'), ('Pharmacology', 'Pharmacology'), ('Dermatology', 'Dermatology'), ('Vascular Surgery', 'Vascular Surgery'), ('Rheumatology', 'Rheumatology'), ('Endocrinology', 'Endocrinology'), ('Neurology', 'Neurology'), ('Hepatology', 'Hepatology'), ('Pulmonology', 'Pulmonology'), ('Infectious Disease', 'Infectious Disease'), ('Immunology', 'Immunology'), ('Orthopedics', 'Orthopedics'), ('Cardiology', 'Cardiology'), ('Gastroenterology', 'Gastroenterology'), ('Urology', 'Urology')], max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=255, verbose_name='Email')),
                ('symptom1', models.CharField(max_length=200)),
                ('symptom2', models.CharField(max_length=200)),
                ('symptom3', models.CharField(max_length=200)),
                ('symptom4', models.CharField(max_length=200)),
                ('symptom5', models.CharField(max_length=200)),
                ('diseases', models.JSONField()),
                ('departments', models.JSONField()),
                ('name', models.CharField(max_length=200)),
            ],
        ),
    ]
