# Generated by Django 5.0.3 on 2024-06-04 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_doctor_history'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='departments',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='history',
            name='diseases',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
