# Generated by Django 5.0.3 on 2024-06-04 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_history_departments_alter_history_diseases'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='email',
            field=models.EmailField(max_length=255, verbose_name='email'),
        ),
    ]
